const verses = {
    happy: [
        "मात्रास्पर्शास्तु कौन्तेय शीतोष्णसुखदुःखदाः (BG 2.14) The contact of the senses with their objects, O son of Kunti, gives rise to cold and heat, pleasure and pain. (Sensory joys are temporary)",
        "यं हि न व्यथयन्त्येते पुरुषं पुरुषर्षभ (BG 2.15) That person who is not disturbed by these, O best among men, is fit for liberation. (Equanimity brings true happiness)",
        "सुखमात्यन्तिकं यत्तद् बुद्धिग्राह्यमतीन्द्रियम् (BG 6.21) That supreme happiness, which is perceived by the intellect and beyond the senses, is attained. (Inner joy transcends senses)",
        "यस्मिन् स्थितो न दुःखेन गुरुणापि विचाल्यते (BG 6.22) Established in which, one is not shaken even by the heaviest sorrow. (Stability yields lasting happiness)",
        "समः शत्रौ च मित्रे च तथा मानापमानयोः (BG 12.18) Equal to friend and foe, and also to honor and dishonor. (Balanced mind finds joy)",
        "तद् बुद्धयस्तदात्मानस्तन्निष्ठास्तत्परायणाः (BG 5.17) Those whose intellect, self, faith, and refuge are in That, attain peace. (Divine focus brings bliss)",
        "यः सर्वत्रानभिस्नेहस्तत्तत्प्राप्य शुभाशुभम् (BG 2.57) He who is unattached everywhere, unaffected by good or evil fortune. (Detachment fosters serene happiness)",
        "अनन्याश्चिन्तयन्तो मां ये जनाः पर्युपासते (BG 9.22) Those who think of Me alone and worship Me with devotion, I protect. (Devotion ensures joyful security)",
        "सन्तोषं परमं प्राप्नोति यः कर्मणि न निबध्यते (BG 3.17) He who finds satisfaction within and is not bound by actions attains supreme peace. (Self-contentment brings happiness)",
        "मच्चित्तः सर्वदुर्गाणि मत्प्रसादात्तरिष्यसि (BG 18.58) With your mind fixed on Me, by My grace, you will overcome all difficulties. (Faith in divine brings joy)",
        "दुःखेष्वनुद्विग्नमनाः सुखेषु विगतस्पृहः (BG 2.56) One whose mind is undisturbed in misery and free from desire in pleasure. (Calmness leads to happiness)",
        "वीतरागभयक्रोधाः मन्मया मामुपाश्रिताः (BG 4.10) Free from attachment, fear, and anger, absorbed in Me, they attain liberation. (Freedom brings joyful liberation)",
        "सुखदुःखे समे कृत्वा लाभालाभौ जयाजयौ (BG 2.38) Treating alike pleasure and pain, gain and loss, victory and defeat. (Equanimity fosters inner joy)",
        "समः सर्वेषु भूतेषु मद्भक्तिं लभते पराम् (BG 18.54) Being equal to all beings, one attains supreme devotion to Me. (Equality leads to blissful devotion)",
        "योगयुक्तो विशुद्धात्मा विजितात्मा जितेन्द्रियः (BG 5.7) The yogi with a pure soul, self-controlled, and senses subdued, is joyful. (Self-mastery brings happiness)",
        "तं विद्याद् दुःखसंयोगवियोगं योगसंज्ञितम् (BG 6.23) Know that as yoga, which is separation from the union with pain. (Yoga ends sorrow, brings joy)",
        "शक्नोतीहैव यः सोढुं प्राक् शरीरविमोक्षणात् (BG 5.23) He who can endure here, before liberation from the body, finds happiness. (Endurance yields lasting joy)",
        "योऽन्तःसुखोऽन्तरारामस्तथान्तर्ज्योतिरेव यः (BG 5.24) He who is happy within, delights within, and is illumined within, attains freedom. (Inner light brings happiness)",
        "प्रसादे सर्वदुःखानां हानिरस्योपजायते (BG 2.65) In tranquility, all sorrows are destroyed for him. (Peace dissolves sorrow, brings joy)",
        "विहाय कामान् यः सर्वान् पुमांश्चरति निःस्पृहः (BG 2.71) He who abandons all desires and moves free from longing attains peace. (Desirelessness leads to happiness)",
        "मच्चित्तः सततं भक्तस्तस्याहं सुलभः पार्थ (BG 8.14) He whose mind is fixed on Me, ever-devoted, easily attains Me. (Devotion makes divine joy accessible)",
        "तेषां सततयुक्तानां भजतां प्रीतिपूर्वकम् (BG 10.10) To those constantly united, who worship with love, I give understanding. (Love for divine brings happiness)",
        "अनपेक्षः शुचिर्दक्ष उदासीनो गतव्यथः (BG 12.16) Free from expectation, pure, skillful, neutral, and untroubled, he is dear to Me. (Purity brings joyful freedom)",
        "संनियम्य अग्निश्च वातश्च यथा सर्वमिदं जगत् (BG 9.6) As wind moves in space, so all this exists in Me. (Cosmic unity inspires joyful awe)",
        "मय्येव मन आधत्स्व मयि बुद्धिं निवेशय (BG 12.8) Fix your mind on Me alone, place your intellect in Me. (Focus on divine brings bliss)",
        "कर्मण्येवाधिकारस्ते मा फलेषु कदाचन (BG 2.47) Your right is to action alone, never to its fruits. (Action without attachment brings peace)",
        "यदृच्छालाभसन्तुष्टः द्वन्द्वातीतो विमत्सरः (BG 4.22) Content with whatever comes, beyond dualities, free from envy. (Contentment yields joyful freedom)",
        "बुद्ध्या विशुद्धया युक्तो धृत्यात्मानं नियम्य च (BG 18.51) With pure intellect and self-control, one attains the highest. (Clarity and control bring joy)",
        "संनियम्य मनो हृदि निश्चलं याति तत्परः (BG 6.27) Restraining the mind in the heart, he attains unshakable peace. (Mind control brings happiness)",
        "सुखमात्यन्तिकं यत्तत् बुद्धिग्राह्यमतीन्द्रियम् (BG 6.28) That supreme happiness, grasped by intellect, beyond senses, he enjoys. (Transcendental joy is eternal)",
        "नास्ति बुद्धिरयुक्तस्य न चायुक्तस्य भावना (BG 2.66) The uncontrolled have no intellect, nor peace nor happiness. (Control brings joyful peace)",
        "ये तु सर्वं कर्माणि मयि संन्यास्य मत्पराः (BG 12.6) Those who surrender all actions to Me, devoted to Me, attain Me. (Surrender brings blissful union)",
        "मद्भक्तः सङ्गवर्जितः निर्वैरः सर्वभूतेषु यः (BG 11.55) My devotee, free from attachment and enmity to all beings, reaches Me. (Love and peace bring joy)",
        "तेषामहं समुद्धर्ता मृत्युसंसारसागरात् (BG 12.7) I deliver them from the ocean of death and rebirth. (Divine rescue brings happiness)",
        "सत्त्वं सुखे संनयति रजः कर्मणि भारत (BG 14.9) Sattva leads to happiness, rajas to action, O Arjuna. (Goodness fosters joyful state)",
        "यत्तेऽहं प्रियमानाय दद्यामेतत् प्रयत्नतः (BG 10.1) Out of love for you, I give this knowledge with care. (Divine love brings joyful wisdom)",
        "यज्ञदानतपःकर्म न त्याज्यं कार्यमेव तत् (BG 18.5) Acts of sacrifice, charity, and austerity should not be abandoned. (Righteous acts bring happiness)",
        "संन्यासस्तु महाबाहो दुःखमाप्तुमयोगतः (BG 5.6) Renunciation without yoga brings pain, not joy. (Yoga aids joyful renunciation)",
        "सर्वधर्मान् परित्यज्य मामेकं शरणं व्रज (BG 18.66) Abandon all duties, take refuge in Me alone, I will free you. (Surrender brings ultimate joy)",
        "न च मां तानि कर्माणि निबध्नन्ति धनञ्जय (BG 9.9) These actions do not bind Me, O Arjuna. (Divine freedom inspires happiness)",
        "समोऽहं सर्वभूतेषु न मे द्वेष्योऽस्ति न प्रियः (BG 9.29) I am equal to all, with no hatred or favoritism. (Divine equality brings joyful peace)",
        "प्रियो हि ज्ञानिनोऽत्यर्थमहं स च मम प्रियः (BG 7.17) The wise one is exceedingly dear to Me, and I to him. (Mutual love brings happiness)",
        "तपाम्यहं अहं वर्षं निगृह्णाम्युत्सृजामि च (BG 9.19) I give heat, I withhold and send rain, sustaining all. (Divine care brings joyful trust)",
        "क्षेत्रज्ञं चापि मां विद्धि सर्वक्षेत्रेषु भारत (BG 13.2) Know Me as the Knower of the field in all fields. (Divine presence brings bliss)",
        "सर्वमेतदृतं मन्ये यन्मां वदसि केशव (BG 10.14) All that you say, O Krishna, I accept as truth. (Trust in divine brings joy)",
        "सर्वभूतहिते रताः लभन्ते ब्रह्मनिर्वाणम् (BG 5.25) Those delighting in the welfare of all attain liberation. (Compassion leads to happiness)",
        "श्रेयो हि ज्ञानमभ्यासात् ज्ञानाद् ध्यानं विशिष्यते (BG 12.12) Knowledge is better than practice, meditation better than knowledge. (Meditation brings supreme joy)",
        "ब्रह्मण्याधाय कर्माणि सङ्गं त्यक्त्वा करोति यः (BG 5.10) He who offers actions to Brahman, abandoning attachment, is free. (Selfless action brings happiness)",
        "न कर्तृत्वं न कर्माणि लोकस्य सृजति प्रभुः (BG 5.14) The Lord creates neither agency nor actions for the world. (Understanding this brings joyful freedom)",
        "सर्वकर्मफलत्यागं ततः कुरु यतात्मवान् (BG 4.21) Renouncing all fruits of action, act with self-control. (Renunciation leads to happiness)"
    ],
    sad: [
        "शोकस्तं तमसः परं धामति प्रज्ञां व्यपोहति (BG 2.11) Grief clouds wisdom, O Arjuna, leading to darkness. (Sorrow obscures clear understanding)",
        "न त्वेवाहं जातु नासं न त्वं नेमे जनाधिपाः (BG 2.12) Never was I not, nor you, nor these kings. (Eternal soul consoles loss)",
        "देहिनोऽस्मिन्यथा देहे कौमारं यौवनं जरा (BG 2.13) As the embodied soul passes through childhood, youth, and old age. (Impermanence explains life’s sorrows)",
        "जातस्य हि ध्रुवो मृत्युर्ध्रुवं जन्म मृतस्य च (BG 2.27) For one born, death is certain; for one dead, birth is certain. (Cycle of life brings sadness)",
        "प्रजहाति यदा कामान् सर्वान् पार्थ मनोगतान् (BG 2.55) When one discards all desires of the mind, O Partha. (Desires cause sorrow)",
        "नैनं छिन्दन्ति शस्त्राणि नैनं दहति पावकः (BG 2.23) Weapons do not cut it, fire does not burn it. (Soul’s eternity eases grief)",
        "यं हि न व्यथयन्त्येते पुरुषं पुरुषर्षभ (BG 2.15) He whom these do not afflict, O best of men. (Endurance overcomes sadness)",
        "सङ्गात्सञ्जायते कामः कामात्क्रोधोऽभिजायते (BG 2.62) From attachment arises desire, from desire, anger is born. (Attachment breeds sorrowful anger)",
        "क्रोधाद्भवति सम्मोहः सम्मोहात्स्मृतिविभ्रमः (BG 2.63) From anger comes delusion, from delusion, loss of memory. (Anger deepens sorrow)",
        "नास्ति बुद्धिरयुक्तस्य न चायुक्तस्य भावना (BG 2.66) The uncontrolled have no intellect, nor peace nor happiness. (Lack of control brings sadness)",
        "विषयेन्द्रियसंयोगाद्यत्तदग्रेऽमृतोपमम् (BG 2.14) Sense contact seems sweet at first, then turns to poison. (Fleeting pleasures cause sorrow)",
        "न हि कश्चित्क्षणमपि जातु तिष्ठत्यकर्मकृत् (BG 3.5) No one can remain inactive even for a moment. (Forced action may sadden)",
        "कर्मणो ह्यपि बोद्धव्यं बोद्धव्यं च विकर्मणः (BG 4.17) One must understand action, inaction, and forbidden action. (Confusion in duty brings sorrow)",
        "शरीरवाङ्मनोभिर्यत्कर्म प्रारभते नरः (BG 3.7) Whatever a man begins with body, speech, or mind. (Wrong actions lead to sadness)",
        "यदा यदा हि धर्मस्य ग्लानिर्भवति भारत (BG 4.7) Whenever righteousness declines, O Bharata. (Moral decay saddens world)",
        "शोकमोहौ प्रभवतः संन्यासात्कर्मणस्तथा (BG 5.6) Sorrow and delusion arise from renunciation without yoga. (Unprepared renunciation causes grief)",
        "काम एष क्रोध एष रजोगुणसमुद्भवः (BG 3.37) Desire and anger arise from the mode of passion. (Passion fuels sorrow)",
        "न कर्मणामनारम्भान्नैष्कर्म्यं पुरुषोऽश्नुते (BG 3.4) Not by avoiding action does one attain freedom. (Inaction brings sorrowful stagnation)",
        "दुःखमित्येव यत्कर्म कायक्लेशभयात्त्यजेत् (BG 18.8) Abandoning duty due to bodily pain or fear causes sorrow. (Fearful avoidance breeds sadness)",
        "न हि देहभृता शक्यं त्यक्तुं कर्माण्यशेषतः (BG 18.11) The embodied cannot completely abandon actions. (Forced inaction saddens soul)",
        "तत्र तं बुद्धिसंयोगं लभते पौर्वदेहिकम् (BG 6.43) There he regains the knowledge from his previous body. (Lost progress may sadden)",
        "नष्टं चेत्प्राक्सिद्धं चेत्किं तत्स्याद्विपरीतकम् (BG 6.38) If one falls from yoga, what becomes of him? (Failure brings sorrow)",
        "अर्जुन उवाच किं तद्ब्रह्म किमध्यात्मं किं कर्म (BG 8.1) Arjuna said: What is Brahman, what is the self, what is action? (Confusion reflects sadness)",
        "न च मां तानि कर्माणि निबध्नन्ति धनञ्जय (BG 9.9) These actions do not bind Me, O Dhananjaya. (Divine detachment contrasts human sorrow)",
        "मोहाद्गृह्यन्ते नरकमिन्द्रियाणि परन्तप (BG 16.11) Delusion leads to hellish suffering, O Parantapa. (Delusion deepens sadness)",
        "आशापाशशतैर्बद्धाः कामक्रोधपरायणाः (BG 16.12) Bound by hundreds of desires, driven by lust and anger. (Desires bind in sorrow)",
        "प्रवृत्तिं च निवृत्तिं च जनान्न विदुरासुराः (BG 16.7) Demonic people know neither action nor renunciation. (Ignorance causes sorrow)",
        "दम्भो दर्पोऽभिमानश्च क्रोधः पारुष्यमेव च (BG 16.4) Hypocrisy, arrogance, pride, anger, and harshness. (Negative traits bring sadness)",
        "दुःखं संन्यासिनः केचिद्यतयो यान्ति तच्छृणु (BG 5.6) Some ascetics find sorrow in renunciation, hear this. (Renunciation can sadden)",
        "नष्टधर्मास्तथा चान्ये संन्यासाद्भवति दुःखम् (BG 18.7) Abandoning prescribed duty causes sorrow, O Arjuna. (Duty neglect brings grief)",
        "कामं क्रोधं लोभं चैव विमुच्य नरकात्प्रभुः (BG 16.21) Freeing from desire, anger, greed saves from hell. (Vices deepen sorrow)",
        "यया स्वप्नमयं विश्वं संनादति च मायया (BG 4.11) By which this world, dream-like, is bewildered by illusion. (Illusion causes sorrow)",
        "न मां दुष्कृतिनो मूढाः प्रपद्यन्ते नराधमाः (BG 7.15) Evil-doers and fools do not surrender to Me. (Ignorance leads to sadness)",
        "त्रिविधं नरकस्येदं द्वारं नाशनमात्मनः (BG 16.21) Three gates of hell destroy the self: lust, anger, greed. (Self-destruction brings sorrow)",
        "यदहङ्कारमाश्रित्य न योत्स्य इति मन्यसे (BG 18.59) If, relying on ego, you think, ‘I will not fight.’ (Ego causes sorrowful conflict)",
        "शोकं च मोहं च जहाति सर्वं यदा विद्वान् (BG 5.28) When the wise one abandons sorrow and delusion fully. (Wisdom heals sadness)",
        "न च्छेदति संमोहो बुद्धिं संनाशति चेतसः (BG 2.63) Delusion destroys intellect and memory, O Arjuna. (Delusion fuels sorrow)",
        "नित्यं च समचित्तत्वं इष्टानिष्टोपपत्तिषु (BG 13.9) Constant equanimity toward desired and undesired events. (Unevenness causes sadness)",
        "सङ्कल्पप्रभवान्कामांस्त्यक्त्वा सर्वानशेषतः (BG 6.24) Abandoning all desires born of mental resolve completely. (Desires perpetuate sorrow)",
        "दुःखमेव सर्वं यत्तत्कामेन संनादति (BG 5.22) All that arises from desire ends in sorrow. (Desire leads to grief)",
        "न चैनं कर्मणा बध्यते यस्तु संन्यासति कर्म (BG 4.14) He who renounces action is not bound by it. (Attachment to action saddens)",
        "नष्टं तत्सर्वमेव स्याद्यदि चेत्स्वधर्मात्परः (BG 3.35) All is lost if one abandons his own duty. (Duty loss brings sorrow)",
        "यस्मात्क्षरमतीतोऽहमक्षरादपि चोत्तमः (BG 15.18) I am beyond the perishable and imperishable, supreme. (Impermanence saddens mortals)",
        "शोकं तं सर्वमुत्सृज्य यदा तिष्ठति पण्डितः (BG 2.57) When the wise one discards all sorrow completely. (Sorrow clings without wisdom)",
        "न च मां तानि कर्माणि लिप्यन्ते कर्मभिः कृतैः (BG 4.14) Actions do not taint Me, nor am I bound. (Human bondage causes sadness)",
        "मोहात्तस्य परित्यागो न च कर्मफलेन च (BG 18.9) Abandonment due to delusion, not fruit of action. (Deluded renunciation brings grief)",
        "कुतस्त्वा कश्मलमिदं विषमे समुपस्थितम् (BG 2.2) Whence this dejection in this perilous hour, O Arjuna? (Dejection amidst duty saddens)",
        "न शोचति न काङ्क्षति समः सर्वेषु भूतेषु (BG 12.17) He neither grieves nor desires, equal to all beings. (Grief arises from inequality)",
        "न चैतद्विद्मः कतरन्नो गरीयो यद्वा जयेम (BG 2.6) Nor do we know which is better, to conquer or be conquered. (Uncertainty breeds sorrow)",
        "सङ्गं त्यक्त्वा फलं चैव स तु संन्यासी मतः (BG 6.1) He who abandons attachment and fruit is a true renouncer. (Attachment causes sorrow)"
    ],
    peace: [
        "प्रशान्तमनसं ह्येनं योगिनं सुखमुत्तमम् (BG 6.27) Supreme bliss comes to the yogi whose mind is peaceful. (Peaceful mind brings bliss)",
        "यदा संहरते चायं कूर्मोऽङ्गानीव सर्वशः (BG 2.58) When he withdraws his senses like a tortoise its limbs. (Sense control yields peace)",
        "प्रजहाति यदा कामान् सर्वान् पार्थ मनोगतान् (BG 2.55) When he discards all desires of the mind, O Partha. (Desirelessness brings peace)",
        "विहाय कामान् यः सर्वान् पुमांश्चरति निःस्पृहः (BG 2.71) He who abandons all desires and acts without longing. (Freedom from desire brings peace)",
        "सन्तुष्टः सततं योगी यतात्मा दृढनिश्चयः (BG 6.20) The yogi, ever satisfied, self-controlled, and resolute. (Self-control fosters peace)",
        "यस्मिन् स्थितो न दुःखेन गुरुणापि विचाल्यते (BG 6.22) Established in which, he is unshaken by heavy sorrow. (Inner stability brings peace)",
        "तं विद्याद् दुःखसंयोगवियोगं योगसंज्ञितम् (BG 6.23) Know that as yoga, separation from union with pain. (Yoga brings peaceful detachment)",
        "सुखमात्यन्तिकं यत्तद् बुद्धिग्राह्यमतीन्द्रियम् (BG 6.21) That supreme happiness, perceived by intellect, beyond senses. (Transcendental peace is supreme)",
        "शान्तिं निर्वाणपरमां मत्संस्थामधिगच्छति (BG 6.15) He attains eternal peace, abiding in Me. (Divine union brings peace)",
        "तद् बुद्धयस्तदात्मानस्तन्निष्ठास्तत्परायणाः (BG 5.17) Those with intellect, self, and faith in That attain peace. (Divine focus brings tranquility)",
        "योऽन्तःसुखोऽन्तरारामस्तथान्तर्ज्योतिरेव यः (BG 5.24) He who is happy within, delights within, illumined within. (Inner peace brings liberation)",
        "प्रसादे सर्वदुःखानां हानिरस्योपजायते (BG 2.65) In tranquility, all his sorrows are destroyed. (Tranquility ends sorrow)",
        "दुःखेष्वनुद्विग्नमनाः सुखेषु विगतस्पृहः (BG 2.56) Mind undisturbed in misery, free from desire in pleasure. (Equanimity brings peace)",
        "यं लब्ध्वा चापरं लाभं मन्यते नाधिकं ततः (BG 6.22) Having gained which, he considers no greater gain. (Supreme gain brings peace)",
        "सर्वभूतस्थमात्मानं सर्वभूतानि चात्मनि (BG 6.29) Seeing the self in all beings, and all in the self. (Unity fosters peace)",
        "समः शत्रौ च मित्रे च तथा मानापमानयोः (BG 12.18) Equal to friend and foe, honor and dishonor alike. (Balance brings peaceful mind)",
        "शक्नोतीहैव यः सोढुं प्राक् शरीरविमोक्षणात् (BG 5.23) He who endures here before liberation from the body. (Endurance leads to peace)",
        "नास्ति बुद्धिरयुक्तस्य न चायुक्तस्य भावना (BG 2.66) The uncontrolled lack intellect, peace, and happiness. (Control brings peaceful clarity)",
        "सर्वकर्मफलत्यागं ततः कुरु यतात्मवान् (BG 4.21) Renouncing all fruits of action, act with self-control. (Renunciation brings peace)",
        "यदृच्छालाभसन्तुष्टः द्वन्द्वातीतो विमत्सरः (BG 4.22) Content with whatever comes, beyond dualities, free from envy. (Contentment yields peace)",
        "सङ्कल्पप्रभवान्कामांस्त्यक्त्वा सर्वानशेषतः (BG 6.24) Abandoning all desires born of mental resolve completely. (Desireless state brings peace)",
        "मच्चित्तः सर्वदुर्गाणि मत्प्रसादात्तरिष्यसि (BG 18.58) Mind fixed on Me, you will overcome all difficulties. (Divine faith brings peace)",
        "अनन्याश्चिन्तयन्तो मां ये जनाः पर्युपासते (BG 9.22) Those who think of Me alone and worship devotedly. (Devotion brings peaceful security)",
        "मय्येव मन आधत्स्व मयि बुद्धिं निवेशय (BG 12.8) Fix your mind on Me, place your intellect in Me. (Divine focus brings peace)",
        "सर्वधर्मान् परित्यज्य मामेकं शरणं व्रज (BG 18.66) Abandon all duties, take refuge in Me alone. (Surrender brings ultimate peace)",
        "बुद्ध्या विशुद्धया युक्तो धृत्यात्मानं नियम्य च (BG 18.51) With pure intellect and self-control, he attains peace. (Clarity brings tranquility)",
        "सन्तोषं परमं प्राप्नोति यः कर्मणि न निबध्यते (BG 3.17) He who finds satisfaction within, unbound by action. (Inner satisfaction brings peace)",
        "ये तु सर्वं कर्माणि मयि संन्यास्य मत्पराः (BG 12.6) Those who surrender all actions to Me, devoted. (Surrender brings peaceful union)",
        "न च मां तानि कर्माणि निबध्नन्ति धनञ्जय (BG 9.9) These actions do not bind Me, O Dhananjaya. (Freedom from bondage brings peace)",
        "समोऽहं सर्वभूतेषु न मे द्वेष्योऽस्ति न प्रियः (BG 9.29) I am equal to all, no hatred or favoritism. (Divine equality brings peace)",
        "न शोचति न काङ्क्षति समः सर्वेषु भूतेषु (BG 12.17) He neither grieves nor desires, equal to all. (Equanimity fosters peace)",
        "तेषामहं समुद्धर्ता मृत्युसंसारसागरात् (BG 12.7) I deliver them from the ocean of death. (Divine rescue brings peace)",
        "सत्त्वं सुखे संनयति रजः कर्मणि भारत (BG 14.9) Sattva leads to happiness, rajas to action. (Goodness brings peaceful state)",
        "श्रेयो हि ज्ञानमभ्यासात् ज्ञानाद् ध्यानं विशिष्यते (BG 12.12) Knowledge better than practice, meditation better than knowledge. (Meditation brings deep peace)",
        "ब्रह्मण्याधाय कर्माणि सङ्गं त्यक्त्वा करोति यः (BG 5.10) Offering actions to Brahman, free from attachment. (Selfless action brings peace)",
        "मद्भक्तः सङ्गवर्जितः निर्वैरः सर्वभूतेषु यः (BG 11.55) My devotee, free from attachment, enmity to all. (Love brings peaceful harmony)",
        "सर्वभूतहिते रताः लभन्ते ब्रह्मनिर्वाणम् (BG 5.25) Those delighting in welfare of all attain liberation. (Compassion leads to peace)",
        "न कर्तृत्वं न कर्माणि लोकस्य सृजति प्रभुः (BG 5.14) The Lord creates neither agency nor actions. (Understanding this brings peace)",
        "प्रियो हि ज्ञानिनोऽत्यर्थमहं स च मम प्रियः (BG 7.17) The wise one is dear to Me, I to him. (Mutual love brings peace)",
        "क्षेत्रज्ञं चापि मां विद्धि सर्वक्षेत्रेषु भारत (BG 13.2) Know Me as the Knower in all fields. (Divine presence brings peace)",
        "सर्वमेतदृतं मन्ये यन्मां वदसि केशव (BG 10.14) All you say, O Krishna, I accept as truth. (Trust brings peaceful acceptance)",
        "यज्ञदानतपःकर्म न त्याज्यं कार्यमेव तत् (BG 18.5) Sacrifice, charity, austerity should not be abandoned. (Righteous acts bring peace)",
        "न हि कश्चित्क्षणमपि जातु तिष्ठत्यकर्मकृत् (BG 3.5) No one remains inactive even for a moment. (Balanced action brings peace)",
        "कर्मण्येवाधिकारस्ते मा फलेषु कदाचन (BG 2.47) Your right is to action, not its fruits. (Detachment brings peaceful action)",
        "सङ्गं त्यक्त्वा फलं चैव स तु संन्यासी मतः (BG 6.1) He who abandons attachment and fruit is a renouncer. (Renunciation fosters peace)",
        "नित्यं च समचित्तत्वं इष्टानिष्टोपपत्तिषु (BG 13.9) Constant equanimity toward desired and undesired events. (Evenness brings lasting peace)",
        "तपाम्यहं अहं वर्षं निगृह्णाम्युत्सृजामि च (BG 9.19) I give heat, send rain, sustaining all. (Divine care brings peace)",
        "अनपेक्षः शुचिर्दक्ष उदासीनो गतव्यथः (BG 12.16) Free from expectation, pure, neutral, untroubled. (Purity brings peaceful freedom)",
        "विता रागभयक्रोधा मन्मया मामुपाश्रिताः (BG 4.10) Free from attachment, fear, anger, absorbed in Me. (Freedom brings peaceful liberation)",
        "सर्वं कर्माखिलं पार्थ ज्ञाने परिसमाप्यते (BG 4.33) All actions culminate in knowledge, O Partha. (Knowledge brings peaceful resolution)"
    ],
    anger: [
        "सङ्गात्सञ्जायते कामः कामात्क्रोधोऽभिजायते (BG 2.62) From attachment arises desire, from desire, anger is born. (Attachment breeds anger)",
        "क्रोधाद्भवति सम्मोहः सम्मोहात्स्मृतिविभ्रमः (BG 2.63) From anger comes delusion, from delusion, loss of memory. (Anger clouds judgment)",
        "काम एष क्रोध एष रजोगुणसमुद्भवः (BG 3.37) This desire, this anger, born of the mode of passion. (Passion fuels anger)",
        "दम्भो दर्पोऽभिमानश्च क्रोधः पारुष्यमेव च (BG 16.4) Hypocrisy, arrogance, pride, anger, and harshness. (Anger marks the demonic)",
        "क्रोधं च परित्यज्य शान्तिमाप्नोति नैष्ठिकीम् (BG 5.26) Abandoning anger, he attains lasting peace. (Anger blocks peace)",
        "त्रिविधं नरकस्येदं द्वारं नाशनमात्मनः (BG 16.21) Three gates of hell: lust, anger, greed. (Anger destroys self)",
        "कामक्रोधवियुक्तानां यतीनां यतचेतसाम् (BG 5.26) Free from desire and anger, the disciplined attain liberation. (Freedom from anger liberates)",
        "दुःखमेव सर्वं यत्कामक्रोधेन संनादति (BG 5.22) All arising from desire and anger ends in sorrow. (Anger leads to grief)",
        "नास्ति बुद्धिरयुक्तस्य न चायुक्तस्य भावना (BG 2.66) The uncontrolled lack intellect, peace, and happiness. (Anger disrupts clarity)",
        "रागद्वेषविमुक्तैस्तु विषयेन्द्रियैश्चरन् (BG 2.64) Free from attachment and aversion, he masters senses. (Aversion fuels anger)",
        "प्रशान्तमनसं ह्येनं योगिनं सुखमुत्तमम् (BG 6.27) Supreme bliss comes to the yogi with a peaceful mind. (Anger opposes peace)",
        "आशापाशशतैर्बद्धाः कामक्रोधपरायणाः (BG 16.12) Bound by desires, driven by lust and anger. (Anger binds soul)",
        "कामं क्रोधं लोभं चैव विमुच्य नरकात्प्रभुः (BG 16.21) Freeing from desire, anger, greed saves from hell. (Anger leads to ruin)",
        "द्वौ भूतसर्गौ लोकेऽस्मिन् दैव आसुर एव च (BG 16.6) Two types of beings: divine and demonic, O Arjuna. (Anger marks demonic)",
        "क्रोधाद्भवति संक्षोभः संक्षोभात्स्मृतिविभ्रमः (BG 2.63) From anger arises turmoil, from turmoil, memory loss. (Anger causes chaos)",
        "न चैनं कर्मणा बध्यते यस्तु संन्यासति कर्म (BG 4.14) He who renounces action is not bound by it. (Anger binds through action)",
        "सङ्कल्पप्रभवान्कामांस्त्यक्त्वा सर्वानशेषतः (BG 6.24) Abandoning all desires born of mental resolve. (Desire sparks anger)",
        "यदा संहरते चायं कूर्मोऽङ्गानीव सर्वशः (BG 2.58) When he withdraws senses like a tortoise its limbs. (Sense control curbs anger)",
        "दम्भेनाविद्यया चैव तमोगुणेन संनादति (BG 16.10) Deluded by pride and ignorance, ruled by tamas. (Ignorance fuels anger)",
        "यदहङ्कारमाश्रित्य न योत्स्य इति मन्यसे (BG 18.59) Relying on ego, you think, ‘I will not fight.’ (Ego breeds anger)",
        "शोकं च मोहं च जहाति सर्वं यदा विद्वान् (BG 5.28) When the wise one abandons sorrow and delusion. (Anger ties to delusion)",
        "न मां दुष्कृतिनो मूढाः प्रपद्यन्ते नराधमाः (BG 7.15) Evil-doers and fools do not surrender to Me. (Anger marks ignorance)",
        "सर्वभूतेषु येनैकं भावमव्ययमीक्षते (BG 6.31) Seeing one imperishable essence in all beings. (Unity dissolves anger)",
        "प्रवृत्तिं च निवृत्तिं च जनान्न विदुरासुराः (BG 16.7) Demonic know neither action nor renunciation. (Ignorance breeds anger)",
        "सत्त्वं सुखे संनयति रजः कर्मणि भारत (BG 14.9) Sattva leads to happiness, rajas to action. (Rajas stirs anger)",
        "न शोचति न काङ्क्षति समः सर्वेषु भूतेषु (BG 12.17) He neither grieves nor desires, equal to all. (Desire fuels anger)",
        "दुःखमित्येव यत्कर्म कायक्लेशभयात्त्यजेत् (BG 18.8) Abandoning duty from fear or pain causes anger. (Fear ignites anger)",
        "न हि देहभृता शक्यं त्यक्तुं कर्माण्यशेषतः (BG 18.11) The embodied cannot fully abandon actions. (Forced inaction stirs anger)",
        "मोहाद्गृह्यन्ते नरकमिन्द्रियाणि परन्तप (BG 16.11) Delusion leads senses to hell, O Parantapa. (Delusion breeds anger)",
        "विता रागभयक्रोधा मन्मया मामुपाश्रिताः (BG 4.10) Free from attachment, fear, anger, absorbed in Me. (Anger ends in surrender)",
        "सर्वं कर्माखिलं पार्थ ज्ञाने परिसमाप्यते (BG 4.33) All actions culminate in knowledge, O Partha. (Knowledge calms anger)",
        "यस्मात्क्षरमतीतोऽहमक्षरादपि चोत्तमः (BG 15.18) I am beyond perishable and imperishable, supreme. (Divine truth soothes anger)",
        "नित्यं च समचित्तत्वं इष्टानिष्टोपपत्तिषु (BG 13.9) Constant equanimity toward desired and undesired events. (Unevenness stirs anger)",
        "शान्तिं निर्वाणपरमां मत्संस्थामधिगच्छति (BG 6.15) He attains eternal peace, abiding in Me. (Divine peace ends anger)",
        "सर्वभूतहिते रताः लभन्ते ब्रह्मनिर्वाणम् (BG 5.25) Those delighting in welfare of all attain liberation. (Compassion counters anger)",
        "प्रशान्तात्मा विगतभीर्ब्रह्मचारिव्रते स्थितः (BG 6.14) With tranquil soul, fearless, steadfast in brahmacharya. (Tranquility overcomes anger)",
        "सर्वधर्मान् परित्यज्य मामेकं शरणं व्रज (BG 18.66) Abandon all duties, take refuge in Me. (Surrender dissolves anger)",
        "मच्चित्तः सर्वदुर्गाणि मत्प्रसादात्तरिष्यसि (BG 18.58) Mind fixed on Me, you overcome all difficulties. (Faith calms anger)",
        "अनन्याश्चिन्तयन्तो मां ये जनाः पर्युपासते (BG 9.22) Those who think of Me alone and worship. (Devotion subdues anger)",
        "मय्येव मन आधत्स्व मयि बुद्धिं निवेशय (BG 12.8) Fix your mind on Me, place intellect in Me. (Focus ends anger)",
        "ब्रह्मण्याधाय कर्माणि सङ्गं त्यक्त्वा करोति यः (BG 5.10) Offering actions to Brahman, free from attachment. (Detachment prevents anger)",
        "न कर्तृत्वं न कर्माणि लोकस्य सृजति प्रभुः (BG 5.14) The Lord creates neither agency nor actions. (Understanding this calms anger)",
        "प्रियो हि ज्ञानिनोऽत्यर्थमहं स च मम प्रियः (BG 7.17) The wise one is dear to Me, I to him. (Love dissolves anger)",
        "क्षेत्रज्ञं चापि मां विद्धि सर्वक्षेत्रेषु भारत (BG 13.2) Know Me as the Knower in all fields. (Divine presence soothes anger)",
        "सर्वमेतदृतं मन्ये यन्मां वदसि केशव (BG 10.14) All you say, O Krishna, I accept as truth. (Trust reduces anger)",
        "यदृच्छालाभसन्तुष्टः द्वन्द्वातीतो विमत्सरः (BG 4.22) Content with whatever comes, beyond dualities. (Contentment prevents anger)",
        "श्रेयो हि ज्ञानमभ्यासात् ज्ञानाद् ध्यानं विशिष्यते (BG 12.12) Knowledge better than practice, meditation better than knowledge. (Meditation calms anger)",
        "सङ्गं त्यक्त्वा फलं चैव स तु संन्यासी मतः (BG 6.1) He who abandons attachment and fruit is a renouncer. (Renunciation curbs anger)",
        "न शोचति न काङ्क्षति समः सर्वेषु भूतेषु (BG 12.17) He neither grieves nor desires, equal to all. (Equality ends anger)",
        "सर्वकर्मफलत्यागं ततः कुरु यतात्मवान् (BG 4.21) Renouncing all fruits of action, act with control. (Self-control stops anger)"
    ],
    protection: [
        "सर्वधर्मान् परित्यज्य मामेकं शरणं व्रज (BG 18.66) Abandon all duties, take refuge in Me alone. (Divine refuge protects)",
        "मच्चित्तः सर्वदुर्गाणि मत्प्रसादात्तरिष्यसि (BG 18.58) Mind fixed on Me, you’ll overcome all difficulties. (Divine grace protects)",
        "अनन्याश्चिन्तयन्तो मां ये जनाः पर्युपासते (BG 9.22) Those who think of Me alone, I protect them. (Devotion ensures protection)",
        "तेषामहं समुद्धर्ता मृत्युसंसारसागरात् (BG 12.7) I deliver them from the ocean of death. (Divine rescue protects)",
        "न च मां तानि कर्माणि निबध्नन्ति धनञ्जय (BG 9.9) These actions do not bind Me, O Dhananjaya. (Divine freedom protects)",
        "मय्येव मन आधत्स्व मयि बुद्धिं निवेशय (BG 12.8) Fix your mind on Me, place intellect in Me. (Divine focus protects)",
        "ये तु सर्वं कर्माणि मयि संन्यास्य मत्पराः (BG 12.6) Those who surrender all actions to Me, devoted. (Surrender offers protection)",
        "शान्तिं निर्वाणपरमां मत्संस्थामधिगच्छति (BG 6.15) He attains eternal peace, abiding in Me. (Divine abode protects)",
        "नैनं छिन्दन्ति शस्त्राणि नैनं दहति पावकः (BG 2.23) Weapons do not cut it, fire does not burn. (Soul’s invincibility protects)",
        "प्रियो हि ज्ञानिनोऽत्यर्थमहं स च मम प्रियः (BG 7.17) The wise one is dear to Me, I to him. (Mutual love protects)",
        "क्षेत्रज्ञं चापि मां विद्धि सर्वक्षेत्रेषु भारत (BG 13.2) Know Me as the Knower in all fields. (Divine presence protects)",
        "सर्वमेतदृतं मन्ये यन्मां वदसि केशव (BG 10.14) All you say, O Krishna, I accept as truth. (Trust in divine protects)",
        "विता रागभयक्रोधा मन्मया मामुपाश्रिताः (BG 4.10) Free from attachment, fear, anger, absorbed in Me. (Surrender protects from fear)",
        "न मे विदुः सुरगणाः प्रभवं न महर्षयः (BG 10.2) Neither gods nor sages know My origin. (Divine supremacy protects)",
        "तपाम्यहं अहं वर्षं निगृह्णाम्युत्सृजामि च (BG 9.19) I give heat, send rain, sustaining all. (Divine care protects)",
        "समोऽहं सर्वभूतेषु न मे द्वेष्योऽस्ति न प्रियः (BG 9.29) I am equal to all, no hatred or favoritism. (Divine impartiality protects)",
        "यदा यदा हि धर्मस्य ग्लानिर्भवति भारत (BG 4.7) Whenever righteousness declines, O Bharata. (Divine intervention protects)",
        "परित्राणाय साधूनां विनाशाय च दुष्कृताम् (BG 4.8) To protect the righteous, destroy the wicked. (Divine purpose protects)",
        "मद्भक्तः सङ्गवर्जितः निर्वैरः सर्वभूतेषु यः (BG 11.55) My devotee, free from attachment, enmity to all. (Devotion protects from harm)",
        "सर्वभूतहिते रताः लभन्ते ब्रह्मनिर्वाणम् (BG 5.25) Those delighting in welfare of all attain liberation. (Compassion protects soul)",
        "न कर्तृत्वं न कर्माणि लोकस्य सृजति प्रभुः (BG 5.14) The Lord creates neither agency nor actions. (Divine detachment protects)",
        "सर्वं कर्माखिलं पार्थ ज्ञाने परिसमाप्यते (BG 4.33) All actions culminate in knowledge, O Partha. (Knowledge protects from bondage)",
        "श्रेयो हि ज्ञानमभ्यासात् ज्ञानाद् ध्यानं विशिष्यते (BG 12.12) Knowledge better than practice, meditation better than knowledge. (Meditation protects mind)",
        "ब्रह्मण्याधाय कर्माणि सङ्गं त्यक्त्वा करोति यः (BG 5.10) Offering actions to Brahman, free from attachment. (Selflessness protects from karma)",
        "नित्यं च समचित्तत्वं इष्टानिष्टोपपत्तिषु (BG 13.9) Constant equanimity toward desired and undesired events. (Equanimity protects peace)",
        "यदृच्छालाभसन्तुष्टः द्वन्द्वातीतो विमत्सरः (BG 4.22) Content with whatever comes, beyond dualities. (Contentment protects from turmoil)",
        "सङ्गं त्यक्त्वा फलं चैव स तु संन्यासी मतः (BG 6.1) He who abandons attachment and fruit is a renouncer. (Renunciation protects from bondage)",
        "सर्वकर्मफलत्यागं ततः कुरु यतात्मवान् (BG 4.21) Renouncing all fruits of action, act with control. (Detachment protects soul)",
        "प्रशान्तात्मा विगतभीर्ब्रह्मचारिव्रते स्थितः (BG 6.14) Tranquil soul, fearless, steadfast in brahmacharya. (Fearlessness protects)",
        "कामक्रोधवियुक्तानां यतीनां यतचेतसाम् (BG 5.26) Free from desire and anger, disciplined minds attain. (Discipline protects from harm)",
        "न शोचति न काङ्क्षति समः सर्वेषु भूतेषु (BG 12.17) He neither grieves nor desires, equal to all. (Equality protects from distress)",
        "प्रहृष्यति यदा कामान् सर्वान् पार्थ मनोगतान् (BG 2.55) When he discards all desires of the mind. (Desirelessness protects)",
        "यं हि न व्यथयन्त्येते पुरुषं पुरुषर्षभ (BG 2.15) He whom these do not afflict, O best of men. (Endurance protects)",
        "दुःखेष्वनुद्विग्नमनाः सुखेषु विगतस्पृहः (BG 2.56) Mind undisturbed in misery, free from desire. (Steadiness protects)",
        "प्रसादे सर्वदुःखानां हानिरस्योपजायते (BG 2.65) In tranquility, all sorrows are destroyed. (Tranquility protects from pain)",
        "शक्नोतीहैव यः सोढुं प्राक् शरीरविमोक्षणात् (BG 5.23) He who endures here before liberation. (Endurance protects soul)",
        "सर्वभूतस्थमात्मानं सर्वभूतानि चात्मनि (BG 6.29) Seeing self in all, all in self. (Unity protects from harm)",
        "सत्त्वं सुखे संनयति रजः कर्मणि भारत (BG 14.9) Sattva leads to happiness, rajas to action. (Goodness protects peace)",
        "यस्मिन् स्थितो न दुःखेन गुरुणापि विचाल्यते (BG 6.22) Established in which, unshaken by sorrow. (Stability protects)",
        "सुखमात्यन्तिकं यत्तद् बुद्धिग्राह्यमतीन्द्रियम् (BG 6.21) Supreme happiness, perceived by intellect, beyond senses. (Transcendence protects)",
        "तद् बुद्धयस्तदात्मानस्तन्निष्ठास्तत्परायणाः (BG 5.17) Intellect, self, faith in That attain peace. (Divine alignment protects)",
        "योऽन्तःसुखोऽन्तरारामस्तथान्तर्ज्योतिरेव यः (BG 5.24) Happy within, delights within, illumined within. (Inner light protects)",
        "सर्वं एतदृतं मन्ये यद्वदसि मे हरिः (BG 10.14) All you say, O Hari, I accept. (Faith protects)",
        "न हि कश्चित्क्षणमपि जातु तिष्ठत्यकर्मकृत् (BG 3.5) No one remains inactive even a moment. (Right action protects)",
        "कर्मण्येवाधिकारस्ते मा फलेषु कदाचन (BG 2.47) Right to action, not fruits. (Detachment protects)",
        "यदा संहरते चायं कूर्मोऽङ्गानीव सर्वशः (BG 2.58) Withdraws senses like a tortoise its limbs. (Control protects)",
        "सन्तुष्टः सततं योगी यतात्मा दृढनिश्चयः (BG 6.20) Ever satisfied, self-controlled, resolute yogi. (Resolve protects)",
        "नास्ति बुद्धिरयुक्तस्य न चायुक्तस्य भावना (BG 2.66) Uncontrolled lack intellect, peace, happiness. (Control protects)",
        "सर्वं कर्माखिलं पार्थ ज्ञाने परिसमाप्यते (BG 4.33) All actions end in knowledge. (Wisdom protects)",
        "यज्ञदानतपःकर्म न त्याज्यं कार्यमेव तत् (BG 18.5) Sacrifice, charity, austerity not to abandon. (Duty protects)"
    ]
};

let clickCount = 0;

function showMessage(emotion) {
    clickCount++;

    const messageElement = document.getElementById('message');
    if (verses[emotion]) {
        const shlokaArray = verses[emotion];
        const randomShloka = shlokaArray[Math.floor(Math.random() * shlokaArray.length)];
        messageElement.innerHTML = randomShloka.replace(/(\([^)]+\))/g, '<br>$1');
        messageElement.style.opacity = '0';
        setTimeout(() => { messageElement.style.opacity = '1'; }, 10);
    } else {
        messageElement.textContent = "No verse available for this emotion.";
    }

    if (clickCount === 3) {
        const hiddenMessage = document.getElementById('hidden-message');
        hiddenMessage.classList.add('show');
    }
}
